<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>feature</string>
    </array>
    <key>firstLineMatch</key>
    <string>^Feature:(.+)$</string>
    <key>foldingStartMarker</key>
    <string>(Background\:|Scenario\:)</string>
    <key>foldingStopMarker</key>
    <string>^(\r\n|\n)$</string>
    <key>keyEquivalent</key>
    <string>^~B</string>
    <key>name</key>
    <string>Behat</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^\s+\b(And|Given|Then|When)\b</string>
            <key>name</key>
            <string>keyword.control.elements.behat</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(Feature\:|Background\:|Scenario\:)</string>
            <key>name</key>
            <string>keyword.control.feature.behat</string>
        </dict>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#strings</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>regex-double-quoted</key>
        <dict>
            <key>begin</key>
            <string>(?x)"/ (?= (\\.|[^"/])++/[imsxeADSUXu]*" )</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.behat</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(/)([imsxeADSUXu]*)(")</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.behat</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.double-quoted.behat</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>comment</key>
                    <string>Escaped from the regexp – there can also be 2 backslashes (since 1 will escape the first)</string>
                    <key>match</key>
                    <string>(\\){1,2}[.$^\[\]{}]</string>
                    <key>name</key>
                    <string>constant.character.escape.regex.behat</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#interpolation</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.arbitrary-repitition.behat</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.arbitrary-repitition.behat</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\{)\d+(,\d+)?(\})</string>
                    <key>name</key>
                    <string>string.regexp.arbitrary-repitition.behat</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[(?:\^?\])?</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.character-class.behat</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\]</string>
                    <key>name</key>
                    <string>string.regexp.character-class.behat</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#interpolation</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[$^+*]</string>
                    <key>name</key>
                    <string>keyword.operator.regexp.behat</string>
                </dict>
            </array>
        </dict>
        <key>regex-single-quoted</key>
        <dict>
            <key>begin</key>
            <string>(?x)'/ (?= (\\.|[^'/])++/[imsxeADSUXu]*' )</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.behat</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(/)([imsxeADSUXu]*)(')</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.behat</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.single-quoted.behat</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.arbitrary-repitition.behat</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.arbitrary-repitition.behat</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\{)\d+(,\d+)?(\})</string>
                    <key>name</key>
                    <string>string.regexp.arbitrary-repitition.behat</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>Escaped from the regexp – there can also be 2 backslashes (since 1 will escape the first)</string>
                    <key>match</key>
                    <string>(\\){1,2}[.$^\[\]{}]</string>
                    <key>name</key>
                    <string>constant.character.escape.regex.behat</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>Escaped from the behat string – there can also be 2 backslashes (since 1 will escape the first)</string>
                    <key>match</key>
                    <string>\\{1,2}[\\']</string>
                    <key>name</key>
                    <string>constant.character.escape.behat</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[(?:\^?\])?</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.character-class.behat</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\]</string>
                    <key>name</key>
                    <string>string.regexp.character-class.behat</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\\[\\'\[\]]</string>
                            <key>name</key>
                            <string>constant.character.escape.behat</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[$^+*]</string>
                    <key>name</key>
                    <string>keyword.operator.regexp.behat</string>
                </dict>
            </array>
        </dict>
        <key>string-double-quoted</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.behat</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>This contentName is just to allow the usage of “select scope” to select the string contents first, then the string with quotes</string>
            <key>contentName</key>
            <string>meta.string-contents.quoted.double.behat</string>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.behat</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.behat</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#interpolation</string>
                </dict>
            </array>
        </dict>
        <key>string-single-quoted</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.behat</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>meta.string-contents.quoted.single.behat</string>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.behat</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.behat</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\[\\']</string>
                    <key>name</key>
                    <string>constant.character.escape.behat</string>
                </dict>
            </array>
        </dict>
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#regex-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.feature</string>
</dict>
</plist>
